[package]
name = "pomelo-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pomelo-lex = { path = "../pomelo-lex" }
rowan = "0.15"
thiserror = "1"

[dev-dependencies]
expect-test = "1.4" 
