[package]
name = "pomelo-ty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pomelo-hir = { path = "../pomelo-hir" }

[dev-dependencies]
pomelo-parse = { path = "../pomelo-parse" }
