name: Test

on:
  push:
    branches:
    - main 
  pull_request:
    paths:
    - main

jobs:
  test:
    name: Test
    strategy:
      matrix:
        rust:
        - stable
        - beta
        experimental:
        - false
        include:
        - rust: nightly
          experimental: true
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
        default: true
    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-features --all-targets --all
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --all-features --all-targets --all
    - name: Test docs
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --doc
    - name: Check (without default features)
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --workspace --no-default-features
  docs:
    name: Documentation on Github Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        - stable
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
          default: true
      - name: Build Docs 
        uses: actions-rs/cargo@v1
        with:
          command: doc 
          args: --workspace --document-private-items --no-deps -p pomelo -p pomelo-*
          env: RUSTDOCFLAGS=--cfg="docsrs"
      - name: Fix index
        run: |
          rm -rf ./docs
          echo "<meta http-equiv=\"refresh\" content=\"0; url=pomelo\">" > target/doc/index.html
          cp -r target/doc ./docs
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true
